created a layout and basic logic of quiz
postoyanstvo/MovieQuiz-IOS-1 pull request #2
Opened 2023-06-28 20:33 UTC by postoyanstvo

created a layout by storyboard according to demanded design, created basic logic of quiz

2023-06-29 21:23 UTC, protos17 requested changes

2023-06-29 21:23 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +           // код, который мы хотим вызвать через 1 секунду
Здесь необходимо убирать цвет рамки:

self.imageView.layer.borderColor = UIColor.clear.cgColor

2023-06-29 21:23 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
Рекомендую добавить блокировку кнопок

2023-06-29 21:23 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +           self.showNextQuestionOrResults()
А здесь рекомендую добавить разблокировку кнопок

2023-06-29 21:23 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            text: "Рейтинг этого фильма больше чем 6?",
Повторяющийся вопрос рекомендую указать как значение по умолчанию для поля text модели QuizQuestion чтобы предотвратить дублирование кода

2023-06-29 21:23 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    struct QuizQuestion {
Модели принято указывать в отдельном файле. Знаю, что по требованиям весь код должен быть написан в одном файле, но к моделям это не относится

2023-06-29 21:23 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private struct QuizStepViewModel {
Рекомендую указать также в отдельном файле

2023-06-29 21:23 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private struct QuizResultsViewModel {
Эту тоже в отдельный файл лучше перенести

2023-07-02 19:31 UTC, postoyanstvo commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private struct QuizResultsViewModel {
done

2023-07-02 19:31 UTC, postoyanstvo commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private struct QuizStepViewModel {
done

2023-07-02 19:31 UTC, postoyanstvo commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    struct QuizQuestion {
done

2023-07-02 19:32 UTC, postoyanstvo commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +           // код, который мы хотим вызвать через 1 секунду
done

2023-07-02 19:38 UTC, postoyanstvo commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            text: "Рейтинг этого фильма больше чем 6?",
done

2023-07-02 19:51 UTC, postoyanstvo commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +
done

2023-07-02 19:51 UTC, postoyanstvo commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +           self.showNextQuestionOrResults()
done

2023-07-03 14:32 UTC, protos17 approved these changes

2023-07-03 14:32 UTC, protos17 commented on MovieQuiz/Presentation/ClassesStructures.swift
> +struct QuizResultsViewModel {
Рекомендую выровнять код, для этого его выделить и нажать "cmd" + "a"

2023-07-03 14:32 UTC, protos17 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.noButtonView.isEnabled = true
Блокировку и разблокировку кнопок рекомендую вынести в приватный метод, который в аргументе принимал бы булевое значение и исходя из него блокировал или разблокировал бы кнопки

2023-07-06 16:08 UTC, postoyanstvo commented on MovieQuiz/Presentation/ClassesStructures.swift
> +struct QuizResultsViewModel {
done

2023-07-06 16:21 UTC, postoyanstvo commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.noButtonView.isEnabled = true
done

2023-07-06 16:25 UTC, merged